### ISSUE TITLE
Titles to fit page on mobile

### ISSUE THREAD

**Issue by dsegovia90** [sego90/slack-timezoner#21]
Titles jump lines, maybe we could make the text smaller to fit the screen.

![image](https://user-images.githubusercontent.com/14206991/29140645-d7ba0f2e-7d10-11e7-9eba-eb8ec779bd2d.png)

**Comment by jdrichardstech** [comment]
I fixed this in the margin-issue branch already

**Comment by dsegovia90** [comment]
Nice, check it in my phone and it works.
