### ISSUE TITLE
rename title

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#26]
An app named Timezoner is already in the app store on slack
Title should probably be Slack Timezoner as originally created by sego90

**Comment by dsegovia90** [comment]
Let me think of something more clever.

**Comment by dsegovia90** [comment]
Proposing the name of Chronus Cronus or Kronos. It's kinda serious though, maybe we want something more playful. Or go full sleek and serious. @jdrichardstech tell me your thoughts.

**Comment by jdrichardstech** [comment]
TimeShooter, TimeCruncher, Kronoscruncher, Cronoscruncher, Galactic,TimeShooter, TimeCruncher, TimeResolver, TimeResolve, OnTheReg (slang for on the regular) , Krone, Kroner, Kronis, TheKrone.... none as awesome as Kronos but all available in slack and heroku.. I like the two syllable idea like Kronos. powerful. Maybe Kronis because it sounds similar to Kronos? But is it more user friendly to have a name like Timetranslator where a user  immediately understands the apps use?

**Comment by jdrichardstech** [comment]
Timetranslator, Timeresolver or Kronis my vote.  either way the slack app, heroku app & app title should all be same name to avoid user confusion & be easy to remember/lookup.

**Comment by dsegovia90** [comment]
Let's go with Kronis, so we can publish the app to the slack app directory. I think it would be a great milestone for us.

**Comment by jdrichardstech** [comment]
One last suggestion: I was always taught not to have to teach a user what something is otherwise they don't find the product. Also, it's already been popularized in Chingu as Timezoner. So what about....
Kronos Timezoner? 
everything is available under that name including the .com and still sounds impactful.
Too much?
Will take your final word. And then will set whatever name accordingly from the Chingu-Bears-1 Slack Team and send you invitation for heroku, slack and team? ...am i missing one?

**Comment by dsegovia90** [comment]
I like Kronos Timezoner. Sounds nice. And yeah, the heroku can stay the same actually. Just change to a new slack group maybe? I like it JD. And we can split the cost of the .com domain if you wish.

**Comment by jdrichardstech** [comment]
is it more consistent and easier for the user if we change the heroku name to kronostimezoner so that the user isn't confused with a uri called slacktimezoner.herokuapp.com? instead the user looks for kronostimezoner accross all platforms?

**Comment by dsegovia90** [comment]
it's irrelevant. we can actually buy a domain of kronostimezoner.com or kronos-timezoner.com and link it ot heroku.

**Comment by dsegovia90** [comment]
we can switch the app name too meanwhile, it's a good idea..
