### ISSUE TITLE
install-thank you redirect

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#28]
create a thank you page redirect for after install

**Comment by jdrichardstech** [comment]
created thanks page on install-thank branch

**Comment by dsegovia90** [comment]
Fixed issues and redirecting to / in case of failed install. Also sending a message. 
![image](https://user-images.githubusercontent.com/14206991/29201044-4ee276a8-7e20-11e7-924e-600df4990d9b.png)
