### ISSUE TITLE
count not incrementing in heroku db on install

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#38]
Wiped heroku db for consistency after team was added.

Installed Timezoner to 2 slack teams several times. team.count is still at 0

![screen shot 2017-08-12 at 1 08 13 pm](https://user-images.githubusercontent.com/1908887/29242700-77ead122-7f5f-11e7-894c-237137dbde42.png)

**Comment by dsegovia90** [comment]
yeah, I think it has something to do with the default in the model. We need to check that out! I want that data! haha

**Comment by dsegovia90** [comment]
I don't know if we deliberately fixed this, but it's now working @jdrichardstech ?

**Comment by jdrichardstech** [comment]
now working
