### ISSUE TITLE
change nav dropdown background on mobile

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#39]
nav dropdown background on mobile needs to be a different color

![dropdown-color-300](https://user-images.githubusercontent.com/1908887/29242733-15fd0e98-7f60-11e7-92a8-1c4f926d32c8.png)

**Comment by dsegovia90** [comment]
Black and white text would do I think. I'll create a branch and fix this quick.

**Comment by dsegovia90** [comment]
Pushed to master.
