### ISSUE TITLE
support page margin issue

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#40]
margin for the support text needs to be adjusted for mobile

![support-margin-300](https://user-images.githubusercontent.com/1908887/29242737-356aa268-7f60-11e7-93ac-0e71a379e986.png)

**Comment by dsegovia90** [comment]
Issue seems fixed. I think you fixed it in another branch. 
![screenshot_20170817-125452](https://user-images.githubusercontent.com/14206991/29426251-a8b5a01c-834b-11e7-949c-84da9d7a19de.png)
