### ISSUE TITLE
add download count to navbar

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#45]
count updates when page is reloaded if app has been installed by a team.

**Comment by dsegovia90** [comment]
the count I implemented (which right now is bugged) counts the number of times the app has translated the time. We could also count the slack groups that have installed the app with a .length of the database

**Comment by jdrichardstech** [comment]
got it. will make a note to reflect that on the navbar. we can add the #of slack groups that have installed later

**Comment by dsegovia90** [comment]
I think we can close this issue, since it's on production now.
