### ISSUE TITLE
Update the .gif image to accommodate the new logos. 

### ISSUE THREAD

**Issue by dsegovia90** [sego90/slack-timezoner#64]
We need to record another gif. Maybe we should do so in a cohort so it looks nice with the time difference and all. Maybe I send the message and you record @jdrichardstech ?

**Comment by jdrichardstech** [comment]
yeah i agree. i don't know the software people use that do the good ones and no one answered my question in the Chingu. So I used photoshop and quicktime. might need to be pieced together from different screens and edited or something. needs thought

**Comment by dsegovia90** [comment]
I think only you need to "film" it, while I send a time message. An example conversation would be:

JD: Hey Dan, at what time do you think we can schedule the meeting?
Dan: Hey Jd, I think 9:30 am should be good for me.
bot: `translates time`
JD: Cool! It works for me.

Something like that.

**Comment by jdrichardstech** [comment]
Filming it is easy. The issue is that the speed of the video as an animated .gif is quite slow.

**Comment by jdrichardstech** [comment]
updated video but still need to update to make more organic.
show 'is typing' below input box and crop video

**Comment by jdrichardstech** [comment]
updated and reduced .gif and in HD.  is this the .gif? or does it still need a little more love?
