### ISSUE TITLE
space am/pm issue

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#65]
When '3:00 pm?' is written. Time translates to 3:00 AM.

**Comment by dsegovia90** [comment]
You fixed this issue in a previous branch didn't you @jdrichardstech ?

**Comment by jdrichardstech** [comment]
no i didn't... so the problem was that we can have a space after the time i.e. 
'3:00 pm' however if you input '3:00 pm?' it returned 3:00 AM. i needed to abstract a substring of the first two indexes of the next word.

**Comment by dsegovia90** [comment]
But I tested this in master and it's working now.

**Comment by jdrichardstech** [comment]
great!
