### ISSUE TITLE
receivedTextArray sometimes undefined

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#77]
The array: receivedTextArray is sometimes being found undefined.

```2017-08-25T21:41:17.537028+00:00 app[web.1]: POST /slack/catchmessages 200 4.502 ms - -
2017-08-25T21:41:17.537488+00:00 app[web.1]: TypeError: Cannot read property 'toLowerCase' of undefined
```

**Comment by jdrichardstech** [comment]
moving declaration of receivedTextArray to within the receivedText conditional in slack.js

**Comment by dsegovia90** [comment]
Huh, this is a weird why is this? Do you know any more info? Or did you fixed it?

**Comment by jdrichardstech** [comment]
i think i fixed it in the hour-am-pm-input branch but we've never merged to production. i never get this error locally

**Comment by jdrichardstech** [comment]
merged
