### ISSUE TITLE
timezoner triggered on non-time input

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#78]
![screen shot 2017-08-26 at 3 24 08 pm](https://user-images.githubusercontent.com/1908887/29744452-f0e7d070-8a72-11e7-860e-9f2a869fa55c.png)

**Comment by dsegovia90** [comment]
yeah, we need to fix that. I see were it triggered. Its on the line => 
```
npm ERR! Unexpected end of input at 1:18918
```
We need to verify that the time does not have any more text next to it. Or maybe think it well. It's translating the *1:18*918

**Comment by dsegovia90** [comment]
How did you catch that error by the way? Lol

**Comment by dsegovia90** [comment]
We should check that the string next to the two digit minutes is pm or am and not anything else. But it's going to be hard to write it in code, and also accept pm with a space before it.

**Comment by jdrichardstech** [comment]
yeah but you still could still have 12:19pm3icej3lkel or 1am3kdlsich
and that will still trigger a time.
this is a tricky bug.
we have two split variables. should we check the length of the index either following the ' : ' and  following the hour number if there is no ' :  ' ?

**Comment by dsegovia90** [comment]
Yeah, it's going to be tricky to function on all cases. But we'll get there.

**Comment by jdrichardstech** [comment]
for now this has been handled. will open new issue when new error occurs
