### ISSUE TITLE
Heroku monitoring add-on

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#87]
Email from Heroku:

Some of your Heroku apps, such as kronostimezoner, have significant development activity or production characteristics, but do not yet have a monitoring add-on installed. | Some of your Heroku apps, such as kronostimezoner, have significant development activity or production characteristics, but do not yet have a monitoring add-on installed.

[https://elements.heroku.com/addons/categories/monitoring?c=7013A000000ia0ZQAQ&utm_campaign=Production-Check-Monitoring&utm_medium=email&utm_source=nurture&utm_content=addons&utm_term=monitoring](https://elements.heroku.com/addons/categories/monitoring?c=7013A000000ia0ZQAQ&utm_campaign=Production-Check-Monitoring&utm_medium=email&utm_source=nurture&utm_content=addons&utm_term=monitoring)

For more information on monitoring and available third party monitoring options, check out the Dev Center visibility and monitoring documentation.All Heroku apps on paid dynos come with Heroku Application Metrics. Heroku makes it easy for you to provision additional monitoring services to your apps via Heroku Elements, the Heroku Dashboard, or the CLI. | For more information on monitoring and available third party monitoring options, check out the Dev Center visibility and monitoring documentation.All Heroku apps on paid dynos come with Heroku Application Metrics. Heroku makes it easy for you to provision additional monitoring services to your apps via Heroku Elements, the Heroku Dashboard, or the CLI. |

**Comment by dsegovia90** [comment]
I think we need a premium version of the Dyno for this to work. I might be wrong.

**Comment by jdrichardstech** [comment]
I wonder if the email was a requirement or a suggestion.
Add-ons and dynos seem like a sudden monthly expense.
A little expensive for the moment no?

**Comment by dsegovia90** [comment]
Yeah, but free dynos are working for us right now. I'm going to close this issue for now. Let's keep monitoring the emails and see if we need to start paying.
